### ISSUE TITLE
-

### ISSUE THREAD

**Issue by victor-cpp** [AeonLucid/RocketLeaguePublic#10]
Default value from ClientRequestEncryptedAppTicketResponse not valid.

**Comment by AeonLucid** [comment]
It does work, make sure you update the headers found here https://github.com/AeonLucid/RocketLeaguePublic#14-headers to their latest ones.

**Comment by cs8coder** [comment]
Just Steam return Ticket length 224, but RL with websocket connection use AuthTicket length 252.
And RL AuthTicket always starts with the same characters - how generate this AuthTicket?
