### ISSUE TITLE
SessionNotActive

### ISSUE THREAD

**Issue by WilliamBlais** [AeonLucid/RocketLeaguePublic#12]
Hello,

On every request to a service other than Auth, I receive the following error:
body: '{"Error":{"Type":"SessionNotActive","Message":""}}'

Sniffing the requests from the game to the API also returns the same error - RL can't connect to the servers.

Does anyone found a solution?

**Comment by nitrog0d** [comment]
They disabled the HTTP API

**Comment by WilliamBlais** [comment]
@nitrog0d Oh no! Do you know how to intercept their websocket?

**Comment by nitrog0d** [comment]
No.
They disabled it for a reason. They don't want people using it. I would advise against attempting to use it further.

**Comment by AeonLucid** [comment]
I'll publish information on the websocket later.

**Comment by Ivekur** [comment]
Any update on websocket?
I tried to use proxycap to make RL use fiddler as a proxy, but i couldn't get it to accept fiddler's cert.

**Comment by AeonLucid** [comment]
@Ivekur Done.

https://github.com/AeonLucid/RocketLeaguePublic/commit/468c7a1e4939541015183b135c9fe2705eb92e4e
