### ISSUE TITLE
How far could this go?

### ISSUE THREAD

**Issue by YEET78** [AeonLucid/RocketLeaguePublic#16]
I have a few people working with things using fortnite endpoints etc, and xmpp requests (as fortnite uses xmpp for message requests), these things can be used in projects like (https://github.com/xmistt/fortnitepy-bot) and its js equivalents, this creates an account in fortnite that can be told how to find certain cosmetics etc. with the file location, and this show up in lobby.
(Its weird talking about fortnite on a RL API), however, i was wondering are these Endpoints used here enough to create a running user on RL, like with fortnite bots?

**Comment by nitrog0d** [comment]
There are bots that use this, like rl exchange and rl deals, so yeah

**Comment by AeonLucid** [comment]
Yes, but you can't go in-game with this as that requires a lot more work. Everything in the lobby can be done with this.
