### ISSUE TITLE
Error: [RocketLeague] Auth failed: {"Responses":[{"ID":1,"Error":{"Type":"VersionMismatch","Message":""}}]}

### ISSUE THREAD

**Issue by johna3212** [AeonLucid/RocketLeaguePublic#17]
[RocketLeague] Auth failed: {"Responses":[{"ID":1,"Error":{"Type":"AccessDenied","Message":""}}]}
I don't know why I am getting this error
       let authRequest = JSON.stringify([
            {
                Service: 'Matchmaking/PlayerSearchPrivateMatch',
                Version: 1,
                Auth: RLKey,
                ID: 1,
                Params: {
                    "Region": "EU"
                }
            }
        ]);

**Comment by millcityrunner** [comment]
Has this issue been resolved yet? I am getting the same error. Please get a fix out there!

**Comment by PinkDraconian** [comment]
This can occur due to many different reasons.
I'd need more information to figure out why this is occurring.

**Comment by Johna-3212** [comment]
I am getting this in every endpoint with Authentication required, else return empty results

**Comment by PinkDraconian** [comment]
> 
> 
> I am getting this in every endpoint with Authentication required, else return empty results

Can you give me more information on what exactly you're doing. Seems like you might not be authorized correctly
Note that the demo.js doesn't work out of the box. 
What do you have buildID and featureSet set to?

**Comment by Johna-3212** [comment]
ok its working after changing buildID but how do you find all these endpoints?

**Comment by PinkDraconian** [comment]
@Johna-3212 , that's something you'd have to ask @AeonLucid 

@AeonLucid I believe this issue can be closed now.
