### ISSUE TITLE
Is this the API that was previously used for rocketleaguestats.com?

### ISSUE THREAD

**Issue by InDieTasten** [AeonLucid/RocketLeaguePublic#2]
If not, what was the API used and what were the pain points?

Was there any communication with Psyonix about the use of the API for stat tracking purposes?

**Comment by AeonLucid** [comment]
No, I did not use this API.  

This seems to answer your question(s) https://www.reddit.com/r/RocketLeague/comments/97p7oh/rlstats_api_shut_down_by_psyonix/e4allxh/.

**Comment by InDieTasten** [comment]
This and linked posts are pretty depressing. Thanks for your work so far though. I really think a proper stats api would benefit the community around rocket league. oh well...
