### ISSUE TITLE
Network Traffic not showing up in Fiddler

### ISSUE THREAD

**Issue by trister1997** [AeonLucid/RocketLeaguePublic#23]
So ive written a project around your findings to get stats for Steam, PS4, and Xbox. I appreciate all the work finding this information!

I was trying to figure out how to get the requests to go through fiddler so I could use your proxy and fiddler script to dump the requests, but I think its because the game uses UDP instead of TCP.
How would I get the requests to show up in fiddler? Force the game to TCP or make the game use some proxy or something?

Thanks!

**Comment by Jawschamp** [comment]
You can't force a game to use TCP

**Comment by itsjafer** [comment]
I have the same problem right now, would love help from anyone that was able to intercept the network traffic

**Comment by SD4RK** [comment]
Actually, if you will use WireShark you'll find the requests that are made to rl api, they still use TCP protocol though. Unfortunately, they're encrypted. Don't know why Charles/HTTPDebugger/Fiddler can't intercept those. 

A workaround may be to hook the Unreal Engine's ProccessEvent function and trace internal calls of the game to HTTP/WS functions, like UPsyNetMessengerHttp_X::SendMessageW and UPsyNetMessengerWebSocket_X::SendMessageW.
I've generated a working SDK and got ProcessEvent hook to working, exploring how to trace this requests atm.

**Comment by SD4RK** [comment]
You're still able to get service calls by generating SDK for the game and hooking Unreal Engine's PE function, hook looks like:
```cpp
void __fastcall HookedProcessEvent(UObject* pObject, UFunction* pFunction, void* pParms, void* pResult) {
	if (pFunction) {
		if (strcmp(pFunction->GetFullName().c_str(), "Function ProjectX.RPCQueue_X.CreateBatch") == 0) {
                        // Should be a global variable.
			rpc_queue = (URPCQueue_X*)pObject;
		}
	}

	if (rpc_queue != nullptr) {
		// Get all the pending batches.
		auto pending_batches = rpc_queue->PendingBatches;
		for (auto i = 0u; i < pending_batches.Num(); ++i) {
			auto batch = pending_batches.At(i);
			if (batch == nullptr) continue;
			if (batch->Requests.Num() <= 0) continue;
			auto request_data = batch->RequestMessage;

			// Parse request's body.
			auto request_body = request_data->Body;
			std::ostringstream body_stream;
			for (auto j = 0u; j < request_body.Num(); ++j) {
				body_stream << (char)request_body.At(j);
			}
			auto body = body_stream.str();

			auto service_name_end = body.find("\"", 13);
			auto service_name = body.substr(13, service_name_end - 13);

			// We already logged this service call. (logged_services is global std::set<std::string>).
			if (logged_services.find(service_name) != logged_services.end()) continue;

			// TODO: PARSE HEADERS.

			// Compose a string about the request.
			ConsolePrintf("Service %s : %s\n", service_name.c_str(), body.c_str());
			logged_services.insert(service_name);
		}
	}

	// Call original function so it can process our data.
	ProcessEventOriginal(pObject, pFunction, pParms, pResult);
}
```
Will cleanup my code a bit and release this services logger.

Most of the services are still look the same as in the repo, but Auth/AuthPlayer is changed, and yeah, now you need EpicAccountID and EpicAuthTicket. The key for HMAC signature and the other request info (except buildid and featureset) is, however, not changed. So I was able to auth on the servers by using Python + requests, just need to figure out how to get an EpicAuthTicket, that is hard though, because we need to reverse some EOS logic.

**Comment by pgsleepy** [comment]
A bit late, just want to add my two cents to the conversation.

> I think its because the game uses UDP instead of TCP.

Forcing the WebSocket connection to fail doesn't work anymore, it'll fallback regardless.
This in turn means forcing HTTPS doesn't work either, WebSocket requests run on TCP which is what we receive.

I've tried to intercept WS packets through Fiddlr to no avail and I've tried countless of methods, it may be my expertise but I had no success in getting these.

Been still looking for it.

**Comment by SD4RK** [comment]
You can hook the ProcessEvent (detour it, address = "4C 8B F1 E8 ?? ?? ?? ?? 85 C0 0F 84" - 0x4A) function. In your hook redirect the connection to your local server:
```cpp
	void __fastcall hooks::hooked_process_event( UObject* object, UFunction* function, void* params, void* result ) {

		if (function) {
                        if (strcmp(function->GetFullName().c_str(), "Function ProjectX.PsyNetConnection_X.HandleUrlChanged") == 0) {
				conn = (UPsyNetConnection_X*)object;
			}
		}

		if (conn) {
                        // Change it every tick just incase.
			conn->URL->URLv2 = FString(L"http://127.0.0.1/rpc");
		}
        }
```
On your localhost run the HTTP&WS mitm servers. Something like that would do the work: https://gist.github.com/SD4RK/94edba56876a45fffd30fc1a2a09727b (code is dirty; should have Python+flask+websockets installed).
This is a dirty workaround but it works.

**Comment by pgsleepy** [comment]
@SD4RK Could you maybe add me on Discord? PGSleepy#2108

**Comment by pgsleepy** [comment]
> You can hook the ProcessEvent (detour it, address = "4C 8B F1 E8 ?? ?? ?? ?? 85 C0 0F 84" - 0x4A) function. In your hook redirect the connection to your local server:
> 
> ```c++
> 	void __fastcall hooks::hooked_process_event( UObject* object, UFunction* function, void* params, void* result ) {
> 
> 		if (function) {
>                         if (strcmp(function->GetFullName().c_str(), "Function ProjectX.PsyNetConnection_X.HandleUrlChanged") == 0) {
> 				conn = (UPsyNetConnection_X*)object;
> 			}
> 		}
> 
> 		if (conn) {
>                         // Change it every tick just incase.
> 			conn->URL->URLv2 = FString(L"http://127.0.0.1/rpc");
> 		}
>         }
> ```
> 
> On your localhost run the HTTP&WS mitm servers. Something like that would do the work: https://gist.github.com/SD4RK/94edba56876a45fffd30fc1a2a09727b (code is dirty; should have Python+flask+websockets installed). This is a dirty workaround but it works.

@SD4RK - I've been looking around, not too familiar with C++ but I am similar with other languages so I'm able to read it sort of.
Are you using an SDK? 

I've tried to maybe get this working with BakkesMod through 

`gameWrapper->HookEventPost("Function ProjectX.PsyNetConnection_X.HandleUrlChanged", std::bind(&WSRedirectPlugin::HookPsyNet, this));`

But have not yet been able to convert your function and conn part yet.
Thanks for your reply and detailed explanation, but I think I'm not quite figuring it out properly yet lol

Could you maybe add me on Discord? PGSleepy#2108

**Comment by pgsleepy** [comment]
@SD4RK Hey, could you maybe add me on Discord? PGSleepy#2108 ^^

**Comment by Jawschamp** [comment]
Just wondering, did we ever find anything useful from this PR?

**Comment by pgsleepy** [comment]
> Just wondering, did we ever find anything useful from this PR?

Yes, we did, but not exactly the same way as SD4RK proposed because that required you to reverse an SDK.
Are you trying to get ranked information?

**Comment by Jawschamp** [comment]
One of many sorts of information yes

**Comment by pgsleepy** [comment]
> One of many sorts of information yes

Add me on Discord, QESleepy.

**Comment by pgsleepy** [comment]
> Having the same problem currently

They're preventing MITM attacks through SSL pinning, so you'd have to bypass that.
However, speaking from experience, this is not really a task particularly for beginners.

It took me quite a long time to get it figured out and even then I needed the help of someone else and when I did get it, it ended up being a bit worthless with the information I already knew at the time apart from toying around with intercepting requests and responses.

So if you're looking for just ranks and stats, there are definitely better (and faster) ways of doing that.

**Comment by cowboy-1337** [comment]
I don't care how long it would take, as long as it is possible I'd like to learn how.

(no its not only for ranks and whatnot)

**Comment by cowboy-1337** [comment]
Guess not

**Comment by FeIipeSoares** [comment]
I've been trying to use frida to bypass the certificate validation, but I haven't been able to achieve anything so far.

`Interceptor.attach(Module.getExportByName("SSPICLI.DLL", "InitializeSecurityContextW"), {
                onEnter() {
                    console.log("[*] InitializeSecurityContextW call!");
                },
                onLeave(retval) {
                    let ret = retval.toInt32();
                    console.log(`[*] Original Return: ${ret} (0x${ret.toString(16)})`);
                    if (ret < 0) {
                        console.log("[*] Error detected! Try SEC_E_OK (0)");
                        retval.replace(0);
                    } else if (ret === 0x90312) {
                        console.log("[*] SEC_I_CONTINUE_NEEDED");
                    }
                }
            });`

**Comment by cowboy-1337** [comment]
@FeIipeSoares nobody who knows is willing to help anyone unfortunately, which is why I was never able to figure it out

**Comment by dank** [comment]
If anybody is still interested, I documented how to disable SSL pinning and intercept WebSocket messages in modern Rocket League: https://github.com/dank/rlapi

Also tried to document all the newer endpoints this repo is missing as much as I could.

**Comment by cowboy-13337** [comment]
> If anybody is still interested, I documented how to disable SSL pinning and intercept WebSocket messages in modern Rocket League: https://github.com/dank/rlapi
> 
> Also tried to document all the newer endpoints this repo is missing as much as I could.

your unpin is the only one thats ever worked for me, very useful. thanks
