### ISSUE TITLE
Config issue with demo folder

### ISSUE THREAD

**Issue by Jawschamp** [AeonLucid/RocketLeaguePublic#26]
in ``demo.js`` it references  ``const Config = require('./demo_config');`` I have no clue what that is, if someone could point me in the right direction to fix it that'd be great

**Comment by AeonLucid** [comment]
Create a file `demo_config.json` with the following contents.

```json
{
  "username": "steam username",
  "password": "steam password",
  "displayName": "display name"
}
```
