### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by black5ky99** [AeonLucid/RocketLeaguePublic#27]
Does it still use the same websocket wss://rl-psy.net/ws?PsyConnectionType=Player ? I cant intercept it with frida.

**Comment by YEET78** [comment]
I'm not even sure if the game even uses. https://psyonix-rl.appspot.com/Services as its endpoint anymore due to epic games now having it on their store. 
But that's just from me im sure the creator can tell you more

**Comment by black5ky99** [comment]
I know that they changed theire HTTP endpoint to https://api.rlpp.psynet.gg/Services .
Im now at the point that the API asks for an EpicAuthKey but i dont know yet how to get one.

**Comment by AeonLucid** [comment]
I will update this repository with accurate information soon.

**Comment by YEET78** [comment]
> I will update this repository with accurate information soon.

Thanks Aeon, you gonna be really helpful for my next project if u get this updated :) 👍

**Comment by Trikos** [comment]
@AeonLucid Did you update the repo with the latest infos?
Super cool work

**Comment by black5ky99** [comment]
@Trikos Sadly he did not updated it yet.

**Comment by oofsamy** [comment]
Can confirm, still not working on epic 😞
