### ISSUE TITLE
Still invalid information in this repo

### ISSUE THREAD

**Issue by Jawschamp** [AeonLucid/RocketLeaguePublic#28]
I looked at this code about a mouth ago, and saw that you were planning on updating this with (current) information. Devs and myself included can't get to the next step of developing without updated information. I don't wanna rush you but, if you have some time could you update this with something, in my opinion good first step is to explain the new way to intercept the web socket connection after that we can probably make sense on how to do all this!

**Comment by black5ky99** [comment]
hey, i think this repo is dead now. But if you are still searching this probably can help you:

https://api.tracker.gg/api/v2/rocket-league/standard/profile/platform/playerid

platforms are: psn, steam and xbl

**Comment by itsjafer** [comment]
I've made a pull request  #29 to address some of the out-of-date information, but I still need help intercepting the network requests :)
