### ISSUE TITLE
It would be nice to have documented result schemas as well

### ISSUE THREAD

**Issue by InDieTasten** [AeonLucid/RocketLeaguePublic#3]

**Comment by AeonLucid** [comment]
I won't be doing this but a PR is definitely welcome.
Simply too much work 😄

**Comment by PinkDraconian** [comment]
Added this #20 

There were some endpoints I couldn't get valid responses from (5 or so)

**Comment by PinkDraconian** [comment]
#20 was accepted. Issue can be closed.
