### ISSUE TITLE
Auth/AuthPlayer "ServiceNotFound"

### ISSUE THREAD

**Issue by misterb63** [AeonLucid/RocketLeaguePublic#31]
Hello,
I'm trying to convert your JS app to PHP, and i have an error at the first step.
When i try to send a request on the server, i have this error : 
`{"Responses":[{"ID":1,"Error":{"Type":"ServiceNotFound","Message":""}}]}"`

Here is the code : [https://pastebin.com/TTsA9J7J](https://pastebin.com/TTsA9J7J)

PS : i'm trying to get it for xbox app

Thank you

**Comment by fantik11** [comment]
Facing same error but with demo from this repository. Do you solve it?

**Comment by pgsleepy** [comment]
I have the same issue, anyone?
Everything seems to be fine, but this is what I get in response.
