### ISSUE TITLE
Auth Failed: PlatformAuthError

### ISSUE THREAD

**Issue by pgsleepy** [AeonLucid/RocketLeaguePublic#34]
Anyone know this one?
Just can't figure past this.

**Comment by black5ky99** [comment]
Wich platform are you trying to use? I Guess Epic?

**Comment by pgsleepy** [comment]
> Wich platform are you trying to use? I Guess Epic?

Yeah, Epic.
I copied exact headers and such but to no avail.

On Steam when I do it I get "DatabaseError" as response.

Are you familiar with it? Could you shoot me a message on Discord 'Sleepy`#2108? please?

**Comment by pgsleepy** [comment]
Are you familiar with all of it?
Would you mind maybe shooting me a message on Discord at 'Sleepy`#2108?
