### ISSUE TITLE
Does this conform to the rocket league EULA?

### ISSUE THREAD

**Issue by InDieTasten** [AeonLucid/RocketLeaguePublic#6]
If it doesn't, maybe it would be helpful to others, what the consequences of breaking the EULA might be. I actually don't know the answer, because I skipped reading it every time they update it just like any other sane person does.

Are there other agreements (possibly Steam EULA), that would be violated as well?

As clarification: I am talking about the act of actually running the demo.js, which is pretty much trying to mimic the steam client and the rocket league game client.

**Comment by AeonLucid** [comment]
To answer the question in your title, most likely not for obvious reasons.
